[project]
name = "jjpred"
version = "0.1.0"
authors = [{ name = "Brian Merchant", email = "brianm@janandjul.com" }]
dependencies = [
  "polars>=1.9.0",
  "fastexcel>=0.11.0",
  "sphinx>=8.0.2",
  "jupyter>=1.1.1",
  "notebook>=7.2.1",
  "quarto>=0.1.0",
  "xlsxwriter>=3.2.0",
  "numba>=0.60.0",
  "altair>=5.4.1",
  "scipy>=1.14.1",
  "vegafusion[embed]>=1.6.9",
  "shiny>=1.2.1",
  "faicons>=0.2.2",
  "shinywidgets>=0.3.4",
  "plotly>=5.24.1",
  "ridgeplot>=0.1.30",
  "anywidget>=0.9.13",
  "palmerpenguins>=0.1.4",
  "shinylive>=0.7.1",
  "ipykernel>=6.29.5",
]
readme = "README.md"
requires-python = ">= 3.12"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = ["vega-datasets>=0.9.0"]

[tool.hatch.metadata]
allow-direct-references = true


[tool.hatch.build.targets.wheel]
packages = ["jjpred"]

[tool.ruff]
line-length = 79
extend-include = ["*.ipynb"]
