from jjpred.analysisdefn import (
    AnalysisDefn,
    CurrentSeasonDefn,
)
from jjpred.utils.datetime import Date


FW24_SS25 = CurrentSeasonDefn(FW=24, SS=25)

analysis_defns: dict[Date, AnalysisDefn] = {
    # Date.from_datelike("2025-MAY-20"): AnalysisDefn(
    #     basic_descriptor="analysis",
    #     date="2025-MAY-12",
    #     master_sku_date="2025-MAY-12",
    #     sales_and_inventory_date="2025-MAY-12",
    #     warehouse_inventory_date="2025-MAY-12",
    #     in_stock_ratio_date="2025-MAY-12",
    #     config_date="2025-APR-07",
    #     current_seasons=FW24_SS25,
    #     po_date=None,
    # ),
    Date.from_datelike("2025-MAY-12"): AnalysisDefn(
        basic_descriptor="analysis",
        date="2025-MAY-12",
        master_sku_date="2025-MAY-12",
        sales_and_inventory_date="2025-MAY-12",
        warehouse_inventory_date="2025-MAY-12",
        in_stock_ratio_date="2025-MAY-12",
        config_date="2025-APR-07",
        current_seasons=FW24_SS25,
        po_date=None,
    ),
    Date.from_datelike("2025-MAY-05"): AnalysisDefn(
        basic_descriptor="analysis",
        date="2025-MAY-05",
        master_sku_date="2025-MAY-05",
        sales_and_inventory_date="2025-MAY-05",
        warehouse_inventory_date="2025-MAY-05",
        config_date="2025-APR-07",
        in_stock_ratio_date="2025-APR-28",
        current_seasons=FW24_SS25,
        po_date=None,
    ),
    Date.from_datelike("2025-APR-28"): AnalysisDefn(
        basic_descriptor="analysis",
        date="2025-APR-29",
        master_sku_date="2025-APR-29",
        sales_and_inventory_date="2025-APR-28",
        warehouse_inventory_date="2025-APR-28",
        config_date="2025-APR-07",
        in_stock_ratio_date="2025-APR-01",
        current_seasons=FW24_SS25,
        po_date=None,
    ),
    Date.from_datelike("2025-APR-21"): AnalysisDefn(
        basic_descriptor="analysis",
        date="2025-APR-23",
        master_sku_date="2025-APR-23",
        sales_and_inventory_date="2025-APR-22",
        warehouse_inventory_date="2025-APR-23",
        config_date="2025-APR-07",
        in_stock_ratio_date="2025-APR-01",
        current_seasons=FW24_SS25,
        po_date=None,
    ),
    Date.from_datelike("2025-APR-14"): AnalysisDefn(
        basic_descriptor="analysis",
        date="2025-APR-14",
        master_sku_date="2025-APR-14",
        sales_and_inventory_date="2025-APR-14",
        warehouse_inventory_date="2025-APR-14",
        config_date="2025-APR-07",
        in_stock_ratio_date="2025-APR-01",
        current_seasons=FW24_SS25,
        po_date=None,
    ),
    Date.from_datelike("2025-APR-07"): AnalysisDefn(
        basic_descriptor="analysis",
        date="2025-APR-07",
        master_sku_date="2025-APR-07",
        sales_and_inventory_date="2025-APR-07",
        warehouse_inventory_date="2025-APR-07",
        config_date="2025-APR-07",
        in_stock_ratio_date="2025-APR-01",
        current_seasons=FW24_SS25,
        po_date=None,
    ),
    Date.from_datelike("2025-MAR-31"): AnalysisDefn(
        basic_descriptor="analysis",
        date="2025-APR-01",
        master_sku_date="2025-APR-01",
        sales_and_inventory_date="2025-APR-01",
        warehouse_inventory_date="2025-APR-01",
        config_date="2025-FEB-25",
        in_stock_ratio_date="2025-APR-01",
        current_seasons=FW24_SS25,
        po_date=None,
    ),
    Date.from_datelike("2025-MAR-24"): AnalysisDefn(
        basic_descriptor="analysis",
        date="2025-MAR-24",
        master_sku_date="2025-MAR-24",
        sales_and_inventory_date="2025-MAR-24",
        warehouse_inventory_date="2025-MAR-24",
        config_date="2025-FEB-25",
        in_stock_ratio_date="2025-MAR-11",
        current_seasons=FW24_SS25,
        po_date=None,
    ),
    Date.from_datelike("2025-MAR-17"): AnalysisDefn(
        basic_descriptor="analysis",
        date="2025-MAR-17",
        master_sku_date="2025-MAR-18",
        sales_and_inventory_date="2025-MAR-18",
        warehouse_inventory_date="2025-MAR-17",
        config_date="2025-FEB-25",
        in_stock_ratio_date="2025-MAR-11",
        current_seasons=FW24_SS25,
        po_date=None,
    ),
    Date.from_datelike("2025-MAR-10"): AnalysisDefn(
        basic_descriptor="analysis",
        date="2025-MAR-10",
        master_sku_date="2025-MAR-10",
        sales_and_inventory_date="2025-MAR-10",
        warehouse_inventory_date="2025-MAR-10",
        config_date="2025-FEB-25",
        in_stock_ratio_date="2025-MAR-11",
        current_seasons=FW24_SS25,
        po_date=None,
    ),
    Date.from_datelike("2025-MAR-03"): AnalysisDefn(
        basic_descriptor="analysis",
        date="2025-MAR-03",
        master_sku_date="2025-MAR-03",
        sales_and_inventory_date="2025-MAR-04",
        warehouse_inventory_date="2025-MAR-03",
        config_date="2025-FEB-25",
        in_stock_ratio_date="2025-MAR-11",
        current_seasons=FW24_SS25,
        po_date=None,
    ),
    Date.from_datelike("2025-FEB-24"): AnalysisDefn(
        basic_descriptor="analysis",
        date="2025-FEB-24",
        master_sku_date="2025-FEB-25",
        sales_and_inventory_date="2025-FEB-25",
        warehouse_inventory_date="2025-FEB-24",
        config_date="2025-FEB-25",
        in_stock_ratio_date="2025-FEB-04",
        current_seasons=FW24_SS25,
        po_date=None,
    ),
    Date.from_datelike("2025-FEB-17"): AnalysisDefn(
        basic_descriptor="analysis",
        date="2025-FEB-17",
        master_sku_date="2025-FEB-19",
        sales_and_inventory_date="2025-FEB-18",
        warehouse_inventory_date="2025-FEB-17",
        config_date="2025-FEB-18",
        in_stock_ratio_date="2025-FEB-04",
        current_seasons=FW24_SS25,
        po_date=None,
    ),
    Date.from_datelike("2025-FEB-10"): AnalysisDefn(
        basic_descriptor="analysis",
        date="2025-FEB-10",
        master_sku_date="2025-FEB-10",
        sales_and_inventory_date="2025-FEB-10",
        warehouse_inventory_date="2025-FEB-09",
        config_date="2025-FEB-03",
        in_stock_ratio_date="2025-FEB-04",
        current_seasons=FW24_SS25,
        combine_hca0_hcb0_gra_asg_history=True,
        po_date=None,
    ),
    Date.from_datelike("2025-FEB-03"): AnalysisDefn(
        basic_descriptor="analysis",
        date="2025-FEB-03",
        master_sku_date="2025-FEB-03",
        sales_and_inventory_date="2025-FEB-03",
        warehouse_inventory_date="2025-FEB-04",
        config_date="2025-FEB-03",
        in_stock_ratio_date="2025-FEB-04",
        current_seasons=FW24_SS25,
        combine_hca0_hcb0_gra_asg_history=True,
        po_date=None,
    ),
    Date.from_datelike("2025-JAN-27"): AnalysisDefn(
        basic_descriptor="analysis",
        date="2025-JAN-27",
        master_sku_date="2025-JAN-27",
        sales_and_inventory_date="2025-JAN-27",
        warehouse_inventory_date="2025-JAN-27",
        config_date="2024-NOV-13",
        in_stock_ratio_date="2025-JAN-19",
        current_seasons=FW24_SS25,
        combine_hca0_hcb0_gra_asg_history=True,
        po_date=None,
    ),
    Date.from_datelike("2025-JAN-20"): AnalysisDefn(
        basic_descriptor="analysis",
        date="2025-JAN-20",
        master_sku_date="2025-JAN-21",
        sales_and_inventory_date="2025-JAN-21",
        warehouse_inventory_date="2025-JAN-21",
        config_date="2024-NOV-13",
        in_stock_ratio_date="2025-JAN-19",
        current_seasons=FW24_SS25,
        combine_hca0_hcb0_gra_asg_history=True,
        po_date=None,
    ),
    Date.from_datelike("2025-JAN-06"): AnalysisDefn(
        basic_descriptor="analysis",
        date="2025-JAN-06",
        master_sku_date="2025-JAN-06",
        sales_and_inventory_date="2025-JAN-06",
        warehouse_inventory_date="2025-JAN-06",
        config_date="2024-NOV-13",
        in_stock_ratio_date="2024-DEC-02",
        current_seasons=FW24_SS25,
        combine_hca0_hcb0_gra_asg_history=True,
        po_date=None,
    ),
}


# analysis_defns: dict[Date, FbaRevDefnArgs] = {
#     Date.from_datelike("2025-FEB-17"): FbaRevDefnArgs(
#         analysis_date="2025-FEB-19",
#         dispatch_date="2025-FEB-17",
#         master_sku_date="2025-FEB-19",
#         sales_and_inventory_date="2025-FEB-18",
#         warehouse_inventory_date="2025-FEB-17",
#         config_date="2025-FEB-18",
#         in_stock_ratio_date="2025-FEB-04",
#         prediction_type_meta_date=None,
#         refill_type=RefillType.WEEKLY,
#         current_seasons=FW24_SS25,
#         check_dispatch_date=False,  # alert!
#         website_sku_date="2025-MAR-18",
#         jjweb_reserve_info=JJWebPredictionInfo(
#             reservation_expr=DEFAULT_RESERVATION_EXPR,
#             force_po_prediction_for_reservation=True,
#         ),
#         qty_box_date=None,
#         mon_sale_r_date=None,
#         mainprogram_date=None,
#         use_old_current_period_method=True,
#         extra_refill_config_info=[
#             RefillConfigInfo(["amazon.ca", "amazon.com"], 5, "HCA0-SND-S")
#         ],
#         combine_hca0_hcb0_gra_asg_history=True,
#         match_main_program_month_fractions=False,
#         po_date=None,
#         new_overrides_e=True,
#         extra_descriptor="_primary",
#     ),
#     Date.from_datelike("2025-FEB-10"): FbaRevDefnArgs(
#         analysis_date="2025-FEB-11",
#         dispatch_date="2025-FEB-11",
#         master_sku_date="2025-FEB-10",
#         sales_and_inventory_date="2025-FEB-10",
#         warehouse_inventory_date="2025-FEB-09",
#         config_date="2025-FEB-03",
#         in_stock_ratio_date="2025-FEB-04",
#         prediction_type_meta_date=None,
#         refill_type=RefillType.WEEKLY,
#         current_seasons=FW24_SS25,
#         check_dispatch_date=False,  # alert!
#         website_sku_date="2025-MAR-18",
#         jjweb_reserve_info=None,
#         qty_box_date=None,
#         mon_sale_r_date=None,
#         mainprogram_date=None,
#         use_old_current_period_method=True,
#         extra_refill_config_info=[
#             RefillConfigInfo(["amazon.ca", "amazon.com"], 5, "HCA0-SND-S")
#         ],
#         combine_hca0_hcb0_gra_asg_history=True,
#         match_main_program_month_fractions=False,
#         po_date=None,
#         new_overrides_e=True,
#         extra_descriptor="_primary",
#     ),
#     Date.from_datelike("2025-FEB-03"): FbaRevDefnArgs(
#         analysis_date="2025-FEB-04",
#         master_sku_date="2025-FEB-03",
#         sales_and_inventory_date="2025-FEB-03",
#         dispatch_date="2025-FEB-01",
#         warehouse_inventory_date="2025-FEB-04",
#         config_date="2025-FEB-03",
#         in_stock_ratio_date="2025-FEB-04",
#         refill_type=RefillType.CUSTOM_2025_FEB_03,
#         current_seasons=FW24_SS25,
#         prediction_type_meta_date=None,
#         check_dispatch_date=True,
#         website_sku_date="2025-MAR-18",
#         jjweb_reserve_info=None,
#         qty_box_date=None,
#         mon_sale_r_date=None,
#         mainprogram_date=None,
#         use_old_current_period_method=True,
#         extra_refill_config_info=[
#             RefillConfigInfo(["amazon.ca", "amazon.com"], 5, "HCA0-SND-S")
#         ],
#         combine_hca0_hcb0_gra_asg_history=True,
#         match_main_program_month_fractions=False,
#         po_date=None,
#         new_overrides_e=True,
#         extra_descriptor="_primary",
#     ),
#     Date.from_datelike("2025-JAN-27"): FbaRevDefnArgs(
#         analysis_date="2025-JAN-27",
#         master_sku_date="2025-JAN-27",
#         sales_and_inventory_date="2025-JAN-27",
#         dispatch_date="2025-JAN-27",
#         warehouse_inventory_date="2025-JAN-27",
#         config_date="2024-NOV-13",
#         in_stock_ratio_date="2025-JAN-19",
#         refill_type=RefillType.WEEKLY,
#         current_seasons=FW24_SS25,
#         prediction_type_meta_date=None,
#         check_dispatch_date=True,
#         website_sku_date="2025-MAR-18",
#         jjweb_reserve_info=None,
#         qty_box_date=None,
#         mon_sale_r_date=None,
#         mainprogram_date=None,
#         use_old_current_period_method=True,
#         extra_refill_config_info=[
#             RefillConfigInfo(["amazon.ca", "amazon.com"], 5, "HCA0-SND-S")
#         ],
#         combine_hca0_hcb0_gra_asg_history=True,
#         match_main_program_month_fractions=False,
#         po_date=None,
#         new_overrides_e=True,
#         extra_descriptor="_primary",
#     ),
#     Date.from_datelike("2025-JAN-20"): FbaRevDefnArgs(
#         analysis_date="2025-JAN-21",
#         master_sku_date="2025-JAN-21",
#         sales_and_inventory_date="2025-JAN-21",
#         dispatch_date="2025-JAN-20",
#         warehouse_inventory_date="2025-JAN-21",
#         config_date="2024-NOV-13",
#         in_stock_ratio_date="2025-JAN-19",
#         refill_type=RefillType.WEEKLY,
#         current_seasons=FW24_SS25,
#         prediction_type_meta_date=None,
#         check_dispatch_date=True,
#         website_sku_date="2025-MAR-18",
#         jjweb_reserve_info=None,
#         qty_box_date=None,
#         mon_sale_r_date=None,
#         mainprogram_date=None,
#         use_old_current_period_method=True,
#         extra_refill_config_info=[
#             RefillConfigInfo(["amazon.ca", "amazon.com"], 5, "HCA0-SND-S")
#         ],
#         combine_hca0_hcb0_gra_asg_history=True,
#         match_main_program_month_fractions=False,
#         po_date=None,
#         new_overrides_e=True,
#         extra_descriptor="_primary",
#     ),
#     Date.from_datelike("2025-JAN-06"): FbaRevDefnArgs(
#         analysis_date="2025-JAN-06",
#         master_sku_date="2025-JAN-06",
#         sales_and_inventory_date="2025-JAN-06",
#         dispatch_date="2025-JAN-01",
#         warehouse_inventory_date="2025-JAN-06",
#         config_date="2024-NOV-13",
#         in_stock_ratio_date="2024-DEC-02",
#         refill_type=RefillType.CUSTOM_2025_JAN_06,
#         current_seasons=FW24_SS25,
#         prediction_type_meta_date=None,
#         check_dispatch_date=True,
#         website_sku_date="2025-MAR-18",
#         jjweb_reserve_info=None,
#         qty_box_date=None,
#         mon_sale_r_date=None,
#         mainprogram_date=None,
#         use_old_current_period_method=True,
#         extra_refill_config_info=[
#             RefillConfigInfo(["amazon.ca", "amazon.com"], 5, "HCA0-SND-S")
#         ],
#         combine_hca0_hcb0_gra_asg_history=True,
#         match_main_program_month_fractions=False,
#         po_date=None,
#         new_overrides_e=True,
#         extra_descriptor="_primary",
#     ),
# }
